import { Inter } from "next/font/google"
import "./globals.css"
import { Web3Modal } from "../context/context"
import NftProvider from "../context/nftContext"
import { OverlayProvider } from "../context/overlayContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Closed Ocean",
  description: "Generated by Closed Ocean",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NftProvider>
          <OverlayProvider>
            <Web3Modal>
              {children}
            </Web3Modal>
          </OverlayProvider>
        </NftProvider>
      </body>
    </html>
  )
}